[package]
name = "code-forge"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
derive_more = { version = "1.0.0", features = ["debug", "from"] }
derive_setters = "0.1.6"
ramhorns = "1.0.1"
rig-core = "0.5.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "fs"] }
tower = { version = "0.5.1", features = ["util"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
