[package]
name = "code-forge"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ratatui = { version = "0.25", features = ["crossterm"] }
crossterm = "0.27"
futures = "0.3"
tokio-stream = "0.1"
thiserror = "1.0"
