[package]
name = "forge-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tokio-stream = "0.1"
async-openai = "0.14"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.41"
async-trait = "0.1.83"

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.1"
tokio = { version = "1", features = ["full", "test-util"] }
